config/routes.rb
Rails.application.routes.draw do
  root 'static_page#home'
  get 'users/new'
  get '/signup', to:'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/edit', to: 'users#edit'
  resources :users
  resources :boards do
    resources :responces, only: :create
  end
  resources :testsessions, only: :create
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :user
  has_many :responces
  has_many :board_category_relations
  has_many :categories, through: :board_category_relations
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :title, presence: true, length: { maximum: 50 }
  validates :description, presence: true, length: { maximum: 100 }
end

app/models/board_category_relation.rb
class BoardCategoryRelation < ApplicationRecord
  belongs_to :board
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :board_category_relations, foreign_key: 'category_id'
  has_many :boards, through: :board_category_relations
end

app/models/responce.rb
class Responce < ApplicationRecord
  belongs_to :user
  belongs_to :board
  validates :content, presence: true, length: { maximum: 100 }
  validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :boards
  has_many :responces
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 100 }, format: { with: VALID_EMAIL_REGEX },
            uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def feed
    Board.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  private
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "ログインが必要です"
        redirect_to login_url
      end
    end

    def search
      q = params[:q] 
      @boards = Board.search(name_cont: q).result 
      @responces = Responce.search(name_cont: q).result 
    end

    def boards_search_params
      params.require(:q).permit(:title_cont)
    end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :logged_in_user

  def new
    @board = current_user.boards.build
  end

  def create
    @board = current_user.boards.build(board_params)
    if @board.save
      flash[:success] = "スレッドを作成しました"
      redirect_to root_url
    else
      flash.now[:danger] = "タイトル(1〜50字)と説明文(1〜100字)は必須項目です"
      render 'new'
    end
  end

  def show
    @board = Board.find(params[:id])
    @responce = Responce.new
    @user = User.find_by(id: @board.user_id)
  end

  def index
  end

  private

    def board_params
      params.require(:board).permit(:title, :description, category_ids: [])
    end
end

app/controllers/responces_controller.rb
class ResponcesController < ApplicationController
  before_action :logged_in_user, only: :create

  def create
    @board = Board.find(params[:board_id])
    @responce = @board.responces.build(responce_params)
    @responce.user = current_user
    if @responce.save
      flash[:success] = "レスを投稿しました"
      redirect_to board_path(@board)
    else
      flash[:danger] = "レスは1〜100字以内で入力してください"
      redirect_to board_path(@board)
    end
  end

  private

    def responce_params
      params.require(:responce).permit(:content)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_to root_url
    else
      flash.now[:danger] = "メールアドレスかパスワードが違います"
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController
  def home
    if logged_in?
      @board = current_user.boards.build
      if params[:q] && params[:q].reject{ |key, value| value.blank? }.present?
        @search = Board.ransack(params[:q])
        @feed_items = @search.result
      else
        @search = Board.none.ransack
        @feed_items = current_user.feed
      end
      @url = root_path
    end
  end
end

app/controllers/testsessions_controller.rb
class TestsessionsController < ApplicationController
  def create
    user = User.find_by(email:"test@test.com")
    session[:user_id] = user.id
    flash[:success] = "テストユーザとしてログインしました"
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "登録しました"
      redirect_to root_url
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "更新しました"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "アカウントを削除しました"
    redirect_to root_url
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/responces_helper.rb
module ResponcesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def current_user?(user)
    user && user == current_user
  end

  def logged_in?
    !current_user.nil?
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/helpers/testsessions_helper.rb
module TestsessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/boards/_board.html.erb
<li id="board-<%= board.id %>">
  <span class="title"><%= link_to board.title, board %></span>
  <span class="description"><%= board.description %></span>
  <span class="timestamp"><%= l board.created_at %>に作成</span>
</li>

app/views/boards/new.html.erb
<% provide(:title, 'スレッド作成') %>
<h1>スレッド作成</h1>

<%= form_with(model: @board, local: true) do |f| %>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= f.text_field :title, placeholder: "スレッドタイトルを入力" %>
      <%= f.text_area :description, placeholder: "スレッドの説明を入力" %>
      <%= f.label :category, 'カテゴリ' %>
      <%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) do |category| %> 
        <%= category.label do %>
          <div class="form-inline">
            <%= category.check_box %>
            <%= category.text %>
          </div>
        <% end %>
      <% end %>
      <%= f.submit "スレッドを作成する", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/boards/show.html.erb
<div class="board">
  <div class="show_board" id="board-<%= @board.id %>">
    <span class="title"><%= @board.title %></span>
    <span class="description"><%= @board.description %></span>
    <span>【カテゴリ】</span>
    <% @board.categories.each do |category| %>
      <%= category.name %>
    <% end %>
  </div>

  <div class="responces">
    <% @board.responces.each do |responce| %>
      <div class="responce">
        <span><%= responce.user.name %></span>
        <span><%= l responce.created_at %></span>
        <div class="content"><%= responce.content %></div>
      </div>
    <% end %>
  </div>
  
  <div class="responce_form">
    <%= form_with(model:[@board, @responce]) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <%= f.text_area :content, placeholder: "レスを入力" %>
          <%= f.submit "投稿する", class: "btn btn-primary" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "井戸端掲示板", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to "スレッド作成", '/boards/new', id: "login" %></li>
          <li><%= link_to current_user.name, current_user, id: "login" %></li>
          <li><%= link_to "ログアウト", logout_path, method: :delete, id: "login" %></li>
        <% else %>
          <li><%= link_to "ログイン", login_path, id: "login" %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>井戸端掲示板</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      エラーが<%= object.errors.count %>個あります
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="boards">
    <%= render @feed_items %>
  </ol>
<% end %>

app/views/shared/_search.html.erb
<div class="search">
  <%= search_form_for @search, url: @url do |f| %>
    <%= f.label :title_cont, "スレッド検索" %>
    <%= f.search_field :title_cont %>
    <%= f.submit "検索", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/static_page/home.html.erb
<% if logged_in? %>
  <div class="row">
      <%= render 'shared/search' %>
      <h3>スレッド一覧</h3>
      <%= render 'shared/feed' %>
  </div>
<% else %>
  <div class="center jumbotron">
    <h1>井戸端掲示板へようこそ！</h1>
    <h2>いろいろなことをみんなで語り合いましょう！</h2>

    <%= link_to "新規登録", signup_path, class: "btn btn-lg btn-primary" %>
    <%= link_to "ログイン", login_path, class: "btn btn-lg btn-primary" %>
    <%= link_to "かんたんログイン", testsessions_path, method: :post, class: "btn btn-lg btn-primary" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "プロフィール編集") %>
<h1>プロフィール編集</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :名前 %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :メールアドレス %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :パスワード %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "パスワード（確認）" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "保存する", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, '新規登録') %>
<h1>新規登録</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :名前 %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :メールアドレス %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :パスワード %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :パスワード（確認） %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "登録する", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<h1>
  <%= @user.name %>
</h1>
<p class="edit_user">
  <%= link_to "プロフィール編集", edit_user_path(current_user) %>
</p>
<p class="delete_user">
  <% if @user == current_user %>
    <%= link_to "アカウントを削除する", @user, method: :delete, data: { confirm: "削除してよろしいですか？" } %>
  <% end %>
</p>